# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Jayant/Desktop/HighSpeedArithmetic_project/HighSpeedArithmetic_project.cache/wt [current_project]
set_property parent.project_path C:/Users/Jayant/Desktop/HighSpeedArithmetic_project/HighSpeedArithmetic_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Jayant/Desktop/HighSpeedArithmetic_project/HighSpeedArithmetic_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Jayant/Desktop/HighSpeedArithmetic_project/halfAdder.v
  C:/Users/Jayant/Desktop/HighSpeedArithmetic_project/fullAdder.v
  C:/Users/Jayant/Desktop/HighSpeedArithmetic_project/pgGen.v
  C:/Users/Jayant/Desktop/HighSpeedArithmetic_project/lookAheadLogic.v
  C:/Users/Jayant/Desktop/HighSpeedArithmetic_project/wallace16.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top wallace16 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef wallace16.dcp

catch { report_utilization -file wallace16_utilization_synth.rpt -pb wallace16_utilization_synth.pb }
